#let xiangshan-memblock-series = (
  id: "xiangshan-memblock",
  title: "香山 MemBlock 解读：从访存总图到高风险路径",
  summary: "读香山 MemBlock 的笔记：先建访存总图，再沿接口、LSQ、MMU、DCache、向量访存往下走，最后汇成一份 review 检查表。",
  route: "docs/xiangshan-memblock/",
  thumbnail: "research-log.svg",
  begin-route: "docs/xiangshan-memblock/01-overview/",
  chapters: (
    (
      id: "overview",
      title: "MemBlock 到底是什么：先建立访存总图",
      summary: "从顶层参数块和单元计数入手建立访存总图；三条 load lane 并不对称，各自有兼职。",
      route: "docs/xiangshan-memblock/01-overview/",
      order: 1,
    ),
    (
      id: "interfaces",
      title: "MemBlock 和后端之间的大门：ooo_to_mem / mem_to_ooo",
      summary: "先从 ooo_to_mem / mem_to_ooo 这对边界接口看清 issue、writeback、feedback、wakeup 和 violation，再进内部读连线。",
      route: "docs/xiangshan-memblock/02-interfaces/",
      order: 2,
    ),
    (
      id: "load-store-lsq",
      title: "Load、Store、Std 和 LSQ：一条访存指令是怎么被拆开的",
      summary: "顺着 load、store address、store data 三条拆开的路径往下走；LSQ 在这里管顺序、forward、replay 和 rollback。",
      route: "docs/xiangshan-memblock/03-load-store-lsq/",
      order: 3,
    ),
    (
      id: "mmu-and-permission",
      title: "DTLB、PTW 和 PMP：为什么地址翻译与权限检查在这里集中出现",
      summary: "三组 DTLB、共享 PTW 扇出和 PMPChecker 阵列属于同一个控制层，地址翻译和权限检查在这里集中。",
      route: "docs/xiangshan-memblock/04-mmu-and-permission/",
      order: 4,
    ),
    (
      id: "dcache-sbuffer-uncache",
      title: "DCache、SBuffer 和 Uncache/MMIO：cacheable 与 uncacheable 路径怎么分家",
      summary: "理清 cacheable 流量、store draining 和 uncache/MMIO 请求的分界线，以及这些边界为什么经常是控制 Bug 的藏身处。",
      route: "docs/xiangshan-memblock/05-dcache-sbuffer-uncache/",
      order: 5,
    ),
    (
      id: "vector-memory",
      title: "向量访存为什么更复杂：Split、Merge、Segment 和 FOF",
      summary: "把 split、merge、segment 和 first-fault 的特殊语义串起来，再看它们如何继续复用底下的标量资源。",
      route: "docs/xiangshan-memblock/06-vector-memory/",
      order: 6,
    ),
    (
      id: "review-checklist",
      title: "我会怎么 review MemBlock：一份高风险路径检查框架",
      summary: "把整条阅读路径压缩成可执行的 review 检查表，聚焦 lane ownership、writeback override、rollback 选择和测试切入点。",
      route: "docs/xiangshan-memblock/07-review-checklist/",
      order: 7,
    ),
  ),
)
