#let xiangshan-memblock-series = (
  id: "xiangshan-memblock",
  title: "香山 MemBlock 解读：从访存总图到高风险路径",
  summary: "把 MemBlock 放回香山核内访存子系统里，沿着接口、MMU、LSQ、DCache、向量访存和 review 热点建立一条可复查的阅读路径。",
  route: "docs/xiangshan-memblock/",
  thumbnail: "research-log.svg",
  begin-route: "docs/xiangshan-memblock/01-overview/",
  chapters: (
    (
      id: "overview",
      title: "MemBlock 到底是什么：先建立访存总图",
      summary: "先从顶层单元计数、三条并不对称的 load lane 和总连线关系入手，把 MemBlock 看成访存协调器，而不是一个单独的大 LSU。",
      route: "docs/xiangshan-memblock/01-overview/",
      order: 1,
    ),
    (
      id: "interfaces",
      title: "MemBlock 和后端之间的大门：ooo_to_mem / mem_to_ooo",
      summary: "通过后端边界接口先看清 issue、writeback、feedback、wakeup 和 violation，再往内部模块细读。",
      route: "docs/xiangshan-memblock/02-interfaces/",
      order: 2,
    ),
    (
      id: "load-store-lsq",
      title: "Load、Store、Std 和 LSQ：一条访存指令是怎么被拆开的",
      summary: "顺着 load、store address、store data 三条路径往下看，再理解 LSQ 为什么既不是纯队列，也不是一个附属模块。",
      route: "docs/xiangshan-memblock/03-load-store-lsq/",
      order: 3,
    ),
    (
      id: "mmu-and-permission",
      title: "DTLB、PTW 和 PMP：为什么地址翻译与权限检查在这里集中出现",
      summary: "把三组 DTLB、共享 PTW 扇出和 PMPChecker 阵列放回同一个控制层里，而不是把它们看成零散配件。",
      route: "docs/xiangshan-memblock/04-mmu-and-permission/",
      order: 4,
    ),
    (
      id: "dcache-sbuffer-uncache",
      title: "DCache、SBuffer 和 Uncache/MMIO：cacheable 与 uncacheable 路径怎么分家",
      summary: "理清 cacheable 流量、store draining 和 uncache/MMIO 请求的分界线，以及这些边界为什么经常是控制 Bug 的藏身处。",
      route: "docs/xiangshan-memblock/05-dcache-sbuffer-uncache/",
      order: 5,
    ),
    (
      id: "vector-memory",
      title: "向量访存为什么更复杂：Split、Merge、Segment 和 FOF",
      summary: "把 split、merge、segment 和 first-fault 的特殊语义串起来，再看它们如何继续复用底下的标量资源。",
      route: "docs/xiangshan-memblock/06-vector-memory/",
      order: 6,
    ),
    (
      id: "review-checklist",
      title: "我会怎么 review MemBlock：一份高风险路径检查框架",
      summary: "把整条阅读路径压缩成可执行的 review 检查表，聚焦 lane ownership、writeback override、rollback 选择和测试切入点。",
      route: "docs/xiangshan-memblock/07-review-checklist/",
      order: 7,
    ),
  ),
)
