#let arch-paper-reading-series = (
  id: "arch-paper-reading",
  title: "体系结构论文阅读与方法整理",
  summary: "读体系结构论文的笔记。每篇围绕一个具体问题，把方法、依赖的硬件状态和设计权衡讲清楚，持续补充。",
  route: "docs/arch-paper-reading/",
  thumbnail: "reading-notes.svg",
  begin-route: "docs/arch-paper-reading/01-on-chip-preloading/",
  chapters: (
    (
      id: "on-chip-preloading",
      title: "基于 LA-PC 的 Data Cache Preloading",
      summary: "从 LA-PC 和 RPT 入手，看这类早期 preloading 方案怎么沿预测控制流提前准备数据访问。",
      route: "docs/arch-paper-reading/01-on-chip-preloading/",
      order: 1,
    ),
    (
      id: "feedback-directed-prefetching",
      title: "用运行时反馈调节硬件预取器：Feedback Directed Prefetching",
      summary: "把预取器当成一个需要 runtime feedback 调节的系统：accuracy、lateness、pollution 共同决定 aggressiveness 该开多大。",
      route: "docs/arch-paper-reading/02-feedback-directed-prefetching/",
      order: 2,
    ),
    (
      id: "spatial-memory-streaming",
      title: "Region-level spatial pattern：Spatial Memory Streaming",
      summary: "围绕 spatial pattern、AGT 和 PHT，看 SMS 怎么在大 region 里学习离散 block 组合，而不是只盯着 stride。",
      route: "docs/arch-paper-reading/03-spatial-memory-streaming/",
      order: 3,
    ),
    (
      id: "colt",
      title: "利用 intermediate contiguity 扩大 TLB reach：CoLT",
      summary: "围绕 intermediate contiguity 和 translation reach，看 CoLT 怎么在 base-page TLB 与 superpage 之间找一个更实用的中间点。",
      route: "docs/arch-paper-reading/04-colt/",
      order: 4,
    ),
    (
      id: "store-sets",
      title: "Violation-driven memory dependence prediction：Store Sets",
      summary: "围绕 SSIT、LFST 和 violation-driven learning，看 store sets 怎么在激进执行和错误 replay 之间折中。",
      route: "docs/arch-paper-reading/05-store-sets/",
      order: 5,
    ),
  ),
)
