#import "../../index.typ": *
#import "../series.typ": arch-notes-series
#import "../_defs.typ": *
#import "@preview/tablem:0.3.0": three-line-table
#import "../_diagrams/cache.typ": cache-coherence-example
#import "../_diagrams/coherence.typ": simple-vi-coherence
#show: series-chapter.with(
  arch-notes-series,
  route: "docs/arch-notes/21-cache-coherence/",
  title: "Cache Coherence",
)

== Shared Memory Model

Shared-memory threads communicate by writing and reading common addresses. Private caches replicate blocks, so a processor can otherwise continue reading a stale local copy after another processor has written a new value.

#figure(
  html.frame(cache-coherence-example()),
  caption: [Replicated private-cache copies create the coherence problem. An invalidate protocol grants the writer ownership, invalidates other copies, and forces a later reader to obtain the updated value.],
)

== Hardware Cache Coherence

Broadcast-Based idea:
- A processor/cache broadcasts(through a bus) its write/update to a memory location to all other processors
- Another processor/cache that has the location either updates or invalidates its local copy


== A Very Simple Coherence Scheme

Idea: *All caches “snoop” (observe) each other’s write/read operations. If a processor writes to a block, all others invalidate the block.*

- Write-through, no-write-allocate cache
- Actions of the local processor on the cache block(input): `PrRd`, `PrWr`
- Actions that are broadcast on the bus for the block(output): `BusRd`, `BusWr`

#figure(
  html.frame(simple-vi-coherence()),
  caption: [State transitions for the minimal Valid/Invalid snooping protocol. Blue transitions are initiated by the local processor; the red transition is caused by observing another cache's `BusWr`.],
)

The diagram describes the state of *one cache line in one cache*. `Valid` means that this cache has a usable copy of the block; `Invalid` means that it must not satisfy a processor read from the line. The state is therefore maintained independently in every private cache, while the bus transactions make the copies agree.

Each edge uses the notation *observed event / emitted bus transaction*. The first item is either a local processor request or an event snooped from the bus; the second item is the transaction generated by this cache. `--` means that this cache emits no bus transaction. In particular:
- `Invalid`, `PrRd / BusRd`: a local read miss requests the block; after the returned data fills the line, the line becomes `Valid`.
- `Invalid`, `PrWr / BusWr`: with no write-allocate, the write is sent through the bus to memory without installing the block, so the line remains `Invalid`.
- `Valid`, `PrRd / --`: a local read hits in the cache and needs no bus traffic.
- `Valid`, `PrWr / BusWr`: write-through updates the local copy and broadcasts the new value; the writer keeps the line `Valid`.
- `Valid`, `snoop BusWr / --`: observing another cache's write invalidates this stale copy; snooping itself emits no new transaction.

This intentionally small protocol assumes a *write-through, no-write-allocate* cache. It has no dirty state, ownership state, or shared/exclusive permission distinction, and it does not model cache-to-cache data forwarding. Protocols such as MESI and MOESI add those states and responses so clean sharing, dirty ownership, interventions, and repeated writes can be handled with less unnecessary memory and broadcast traffic.

Lower latency but not scalable.

== Directory-Based Coherence

Idea: *A logically-central directory keeps track of where the copies of each cache block reside. Caches consult this directory to ensure coherence.*

An example mechanism:
- For each cache block in memory, store P+1 bits(P is num of processor) in directory
  - One bit for each cache, indicating whether the block is in cache
  - Exclusive bit: indicates that a cache has the only copy of the block and can update it without notifying others
- On a read: set the cache’s bit and arrange the supply of data
- On a write: invalidate all caches that have the block and reset their bits
- Have an “exclusive bit” associated with each block in each cache (so that the cache can update the exclusive block silently)

Latency is long but scalable and needs addition directory storage.

