#let xiangshan-memblock-series = (
  id: "xiangshan-memblock",
  title: "Reading XiangShan MemBlock: From the Memory Subsystem Map to Review Hotspots",
  summary: "A structured path through MemBlock, MMU, LSQ, DCache, vector memory, and the review hotspots that show up once the code stops looking like a single LSU module.",
  route: "docs/xiangshan-memblock/",
  thumbnail: "research-log.svg",
  begin-route: "docs/xiangshan-memblock/01-overview/",
  chapters: (
    (
      id: "overview",
      title: "What MemBlock Really Is: Building the Memory Subsystem Map First",
      summary: "Start from the top-level unit counts, the non-symmetric load lanes, and the reason MemBlock behaves more like a memory coordinator than a single execution pipe.",
      route: "docs/xiangshan-memblock/01-overview/",
      order: 1,
    ),
    (
      id: "interfaces",
      title: "The Main Boundary to the Backend: ooo_to_mem and mem_to_ooo",
      summary: "Use the backend-facing interface to understand what gets issued into MemBlock, what comes back out, and which feedback paths matter before touching internal details.",
      route: "docs/xiangshan-memblock/02-interfaces/",
      order: 2,
    ),
    (
      id: "load-store-lsq",
      title: "Load, Store, Std, and the LSQ: How One Memory Instruction Gets Split",
      summary: "Follow the split between load, store-address, and store-data paths, then connect that split to the LSQ's role in forwarding, replay, and rollback.",
      route: "docs/xiangshan-memblock/03-load-store-lsq/",
      order: 3,
    ),
    (
      id: "mmu-and-permission",
      title: "DTLB, PTW, and PMP: Why Translation and Permission Checks Converge Here",
      summary: "Read the three DTLB groups, the shared PTW fanout, and the PMPChecker array as one coordinated layer rather than as isolated pieces.",
      route: "docs/xiangshan-memblock/04-mmu-and-permission/",
      order: 4,
    ),
    (
      id: "dcache-sbuffer-uncache",
      title: "DCache, SBuffer, and Uncache/MMIO: Separating Cacheable and Uncacheable Paths",
      summary: "Trace how cacheable traffic, store draining, and uncache/MMIO requests are kept apart, and why their boundaries are easy places for control bugs to hide.",
      route: "docs/xiangshan-memblock/05-dcache-sbuffer-uncache/",
      order: 5,
    ),
    (
      id: "vector-memory",
      title: "Why Vector Memory Is So Much More Complicated: Split, Merge, Segment, and FOF",
      summary: "Connect splitters, merge buffers, segment access, and first-fault behavior to the scalar resources they still need to borrow underneath.",
      route: "docs/xiangshan-memblock/06-vector-memory/",
      order: 6,
    ),
    (
      id: "review-checklist",
      title: "How I Would Review MemBlock: A Checklist for High-Risk Paths",
      summary: "Turn the whole reading path into a practical review checklist for lane ownership, writeback override, rollback selection, and test strategy.",
      route: "docs/xiangshan-memblock/07-review-checklist/",
      order: 7,
    ),
  ),
)
