# Find all page .typ files in content/ while excluding metadata-only files.
SITE_DIR := _site
SITE_ASSET_DIR := $(SITE_DIR)/assets
DEPS_DIR := .deps
PAGEFIND_BIN := ./node_modules/.bin/pagefind
PAGEFIND_FLAGS := --site $(SITE_DIR) --output-subdir pagefind --force-language en
TYPST_HTML_FLAGS := --root .. --features html --format html
TYP_FILES := $(shell find content -name '*.typ' -not -name 'series.typ' -not -name 'registry.typ' -not -path '*/_*' | LC_ALL=C sort)
PORT ?= 8000

# Generate corresponding HTML file paths in the output directory
HTML_FILES := $(patsubst content/%.typ,$(SITE_DIR)/%.html,$(TYP_FILES))
DEP_FILES := $(patsubst content/%.typ,$(DEPS_DIR)/%.d,$(TYP_FILES))
ASSET_FILES := $(shell find assets -type f | LC_ALL=C sort)

# The main target 'html' builds pages, copies assets, and indexes the site for search.
html: $(HTML_FILES) assets search-index

# Explicit target for GitHub Pages style deployments
pages:
	@$(MAKE) clean
	@$(MAKE) html
	@touch $(SITE_DIR)/.nojekyll
	@printf '%s\n' "$(SITE_DIR)"

github-pages: pages

preview:
	@$(MAKE) html
	@python3 -m http.server -d $(SITE_DIR) $(PORT)

# --deps records every file the compilation reads (imports, images, …) as a
# Make rule, giving exact per-page rebuild triggers.
$(SITE_DIR)/%.html: content/%.typ
	@mkdir -p $(@D) $(DEPS_DIR)/$(*D)
	typst compile $(TYPST_HTML_FLAGS) --deps $(DEPS_DIR)/$*.d --deps-format make $< $@

# .d files are generated by the compile rule above; on a fresh build they are
# simply absent. If a stale .d breaks the build after a source file is
# deleted, run `make clean`.
-include $(DEP_FILES)

assets: $(ASSET_FILES)
	@mkdir -p $(SITE_ASSET_DIR)
	@cp -r assets/* $(SITE_ASSET_DIR)/

search-index: $(HTML_FILES) assets package-lock.json
	@test -x $(PAGEFIND_BIN) || (printf '%s\n' "Missing $(PAGEFIND_BIN). Run npm install to set up Pagefind." >&2; exit 1)
	@$(PAGEFIND_BIN) $(PAGEFIND_FLAGS)

# A clean rule to remove generated files
clean:
	rm -rf $(SITE_DIR) $(DEPS_DIR)

.PHONY: html clean assets pages github-pages preview search-index
