#let arch-notes-series = (
  id: "arch-notes",
  title: "Computer Architecture Notes",
  summary: "Thematic notes on simulation, out-of-order and speculative execution, branch prediction, specialized execution models, multiprocessors, interconnects, memory systems, prefetching, and virtual memory.",
  route: "docs/arch-notes/",
  thumbnail: "arch-notes.svg",
  begin-route: "docs/arch-notes/01-architectural-simulation/",
  chapters: (
    (id: "architectural-simulation", title: "Architectural Simulation", summary: "Why architecture needs evaluation, simulation goals, and how models gain credibility.", route: "docs/arch-notes/01-architectural-simulation/", order: 1),
    (id: "precise-exception", title: "Precise Exceptions", summary: "What precise exceptions require and why they are hard in multi-cycle and pipelined machines.", route: "docs/arch-notes/02-precise-exception/", order: 2),
    (id: "out-of-order-execution", title: "Out-of-Order Execution", summary: "Dynamic scheduling, register renaming, and the machinery that preserves precise state.", route: "docs/arch-notes/03-out-of-order-execution/", order: 3),
    (id: "ooo-loads-stores", title: "Out-of-Order Loads and Stores", summary: "Memory disambiguation: when loads may bypass stores and what happens when the guess is wrong.", route: "docs/arch-notes/04-ooo-loads-stores/", order: 4),
    (id: "dataflow-superscalar", title: "Dataflow and Superscalar Execution", summary: "Dataflow graphs and how superscalar cores approximate them with dynamic scheduling.", route: "docs/arch-notes/05-dataflow-superscalar/", order: 5),
    (id: "branch-prediction", title: "Branch Prediction", summary: "Why control flow limits ILP, and the predictors that keep pipelines full.", route: "docs/arch-notes/06-branch-prediction/", order: 6),
    (id: "advanced-branch-prediction", title: "Advanced Branch Prediction", summary: "TAGE, perceptrons, and other predictors used where simple counters stop scaling.", route: "docs/arch-notes/07-advanced-branch-prediction/", order: 7),
    (id: "vliw", title: "VLIW Architectures", summary: "Moving scheduling from hardware to the compiler, and what that trade costs.", route: "docs/arch-notes/08-vliw/", order: 8),
    (id: "systolic-array", title: "Systolic Array Architectures", summary: "Regular dataflow arrays for dense computation, from matrix kernels to modern accelerators.", route: "docs/arch-notes/09-systolic-array/", order: 9),
    (id: "decoupled-access-execute", title: "Decoupled Access-Execute", summary: "Splitting memory access from computation to hide latency with simple hardware.", route: "docs/arch-notes/10-decoupled-access-execute/", order: 10),
    (id: "simd", title: "SIMD Architectures", summary: "Vector and SIMD execution: one instruction stream over many data lanes.", route: "docs/arch-notes/11-simd/", order: 11),
    (id: "gpu", title: "Graphics Processing Units", summary: "Throughput-oriented design, SIMT execution, and the memory system behind it.", route: "docs/arch-notes/12-gpu/", order: 12),
    (id: "multiprocessors", title: "Multiprocessors, Memory Ordering, and Cache Coherence", summary: "Shared-memory machines: coherence, consistency models, and synchronization.", route: "docs/arch-notes/13-multiprocessors/", order: 13),
    (id: "interconnects", title: "Interconnection Networks", summary: "Topology, routing, and flow control for on-chip and system-scale networks.", route: "docs/arch-notes/14-interconnects/", order: 14),
    (id: "memory-organization", title: "Memory Organization and Technology", summary: "DRAM cells, arrays, banks, and the system hierarchy from channel to subarray.", route: "docs/arch-notes/15-memory-organization/", order: 15),
    (id: "memory-hierarchy-caches", title: "Memory Hierarchy and Caches", summary: "Why hierarchies work: locality, levels, and the metrics that describe them.", route: "docs/arch-notes/16-memory-hierarchy-caches/", order: 16),
    (id: "multi-level-cache", title: "Multi-Level Cache Design and Management", summary: "Inclusion, exclusion, and the policies that coordinate cache levels.", route: "docs/arch-notes/17-multi-level-cache/", order: 17),
    (id: "cache-performance", title: "Cache Performance", summary: "AMAT, miss categories, and the standard levers for reducing them.", route: "docs/arch-notes/18-cache-performance/", order: 18),
    (id: "advanced-caching", title: "Advanced Caching", summary: "Replacement policies, partitioning, and other techniques in modern cache design.", route: "docs/arch-notes/19-advanced-caching/", order: 19),
    (id: "multi-core-caches", title: "Multi-Core Caches", summary: "Shared and private cache organization once multiple cores contend for capacity.", route: "docs/arch-notes/20-multi-core-caches/", order: 20),
    (id: "cache-coherence", title: "Cache Coherence", summary: "Coherence protocols, snooping and directories, and how they scale.", route: "docs/arch-notes/21-cache-coherence/", order: 21),
    (id: "emerging-memory", title: "Memory Robustness, Flash, and Emerging Memory", summary: "Reliability mechanisms, NAND flash organization, and new memory technologies.", route: "docs/arch-notes/22-emerging-memory/", order: 22),
    (id: "prefetching", title: "Prefetching", summary: "Hiding memory latency by predicting what data will be needed next.", route: "docs/arch-notes/23-prefetching/", order: 23),
    (id: "virtual-memory", title: "Virtual Memory", summary: "Address translation, TLBs, page tables, and the costs behind each access.", route: "docs/arch-notes/24-virtual-memory/", order: 24),
    (id: "future-architecture", title: "Epilogue: Future Computer Architecture", summary: "Data-centric trends and where architecture appears to be heading.", route: "docs/arch-notes/25-future-architecture/", order: 25),
  ),
)
